//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/15/2017 1:35:31 PM
namespace RuleService.Models
{
    /// <summary>
    /// There are no comments for RuleSingle in the schema.
    /// </summary>
    public partial class RuleSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Rule>
    {
        /// <summary>
        /// Initialize a new RuleSingle object.
        /// </summary>
        public RuleSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RuleSingle object.
        /// </summary>
        public RuleSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RuleSingle object.
        /// </summary>
        public RuleSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Rule> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Variables in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RuleService.Models.RuleVariable> Variables
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Variables == null))
                {
                    this._Variables = Context.CreateQuery<global::RuleService.Models.RuleVariable>(GetPath("Variables"));
                }
                return this._Variables;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RuleService.Models.RuleVariable> _Variables;
    }
    /// <summary>
    /// There are no comments for Rule in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Rule : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Rule object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Rule CreateRule(int ID, string name)
        {
            Rule rule = new Rule();
            rule.Id = ID;
            rule.Name = name;
            return rule;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Expression in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::RuleService.Models.Expressions.Expression Expression
        {
            get
            {
                return this._Expression;
            }
            set
            {
                this.OnExpressionChanging(value);
                this._Expression = value;
                this.OnExpressionChanged();
                this.OnPropertyChanged("Expression");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::RuleService.Models.Expressions.Expression _Expression;
        partial void OnExpressionChanging(global::RuleService.Models.Expressions.Expression value);
        partial void OnExpressionChanged();
        /// <summary>
        /// There are no comments for Property Variables in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::RuleService.Models.RuleVariable> Variables
        {
            get
            {
                return this._Variables;
            }
            set
            {
                this.OnVariablesChanging(value);
                this._Variables = value;
                this.OnVariablesChanged();
                this.OnPropertyChanged("Variables");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::RuleService.Models.RuleVariable> _Variables = new global::Microsoft.OData.Client.DataServiceCollection<global::RuleService.Models.RuleVariable>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnVariablesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::RuleService.Models.RuleVariable> value);
        partial void OnVariablesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RuleVariableSingle in the schema.
    /// </summary>
    public partial class RuleVariableSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<RuleVariable>
    {
        /// <summary>
        /// Initialize a new RuleVariableSingle object.
        /// </summary>
        public RuleVariableSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RuleVariableSingle object.
        /// </summary>
        public RuleVariableSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RuleVariableSingle object.
        /// </summary>
        public RuleVariableSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<RuleVariable> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for RuleVariable in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class RuleVariable : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RuleVariable object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="state">Initial value of State.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static RuleVariable CreateRuleVariable(int ID, string name, bool state)
        {
            RuleVariable ruleVariable = new RuleVariable();
            ruleVariable.Id = ID;
            ruleVariable.Name = name;
            ruleVariable.State = state;
            return ruleVariable;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public bool State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this._State = value;
                this.OnStateChanged();
                this.OnPropertyChanged("State");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _State;
        partial void OnStateChanging(bool value);
        partial void OnStateChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::RuleService.Models.Rule as global::RuleService.Models.RuleSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::RuleService.Models.RuleSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RuleService.Models.Rule> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::RuleService.Models.RuleSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::RuleService.Models.Rule as global::RuleService.Models.RuleSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::RuleService.Models.RuleSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RuleService.Models.Rule> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::RuleService.Models.RuleSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::RuleService.Models.RuleVariable as global::RuleService.Models.RuleVariableSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::RuleService.Models.RuleVariableSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RuleService.Models.RuleVariable> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::RuleService.Models.RuleVariableSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::RuleService.Models.RuleVariable as global::RuleService.Models.RuleVariableSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::RuleService.Models.RuleVariableSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RuleService.Models.RuleVariable> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::RuleService.Models.RuleVariableSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace RuleService.Models.Expressions
{
    /// <summary>
    /// There are no comments for Expression in the schema.
    /// </summary>
    public abstract partial class Expression : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ExpressionVariable in the schema.
    /// </summary>
    public partial class ExpressionVariable : Expression
    {
        /// <summary>
        /// Create a new ExpressionVariable object.
        /// </summary>
        /// <param name="ruleVariableId">Initial value of RuleVariableId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static ExpressionVariable CreateExpressionVariable(int ruleVariableId)
        {
            ExpressionVariable expressionVariable = new ExpressionVariable();
            expressionVariable.RuleVariableId = ruleVariableId;
            return expressionVariable;
        }
        /// <summary>
        /// There are no comments for Property RuleVariableId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int RuleVariableId
        {
            get
            {
                return this._RuleVariableId;
            }
            set
            {
                this.OnRuleVariableIdChanging(value);
                this._RuleVariableId = value;
                this.OnRuleVariableIdChanged();
                this.OnPropertyChanged("RuleVariableId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _RuleVariableId;
        partial void OnRuleVariableIdChanging(int value);
        partial void OnRuleVariableIdChanged();
    }
    /// <summary>
    /// There are no comments for ExpressionUnaryOperation in the schema.
    /// </summary>
    public partial class ExpressionUnaryOperation : Expression
    {
        /// <summary>
        /// Create a new ExpressionUnaryOperation object.
        /// </summary>
        /// <param name="operator">Initial value of Operator.</param>
        /// <param name="operand">Initial value of Operand.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static ExpressionUnaryOperation CreateExpressionUnaryOperation(global::RuleService.Models.Expressions.ExpressionUnaryOperator @operator, global::RuleService.Models.Expressions.Expression operand)
        {
            ExpressionUnaryOperation expressionUnaryOperation = new ExpressionUnaryOperation();
            expressionUnaryOperation.Operator = @operator;
            if ((operand == null))
            {
                throw new global::System.ArgumentNullException("operand");
            }
            expressionUnaryOperation.Operand = operand;
            return expressionUnaryOperation;
        }
        /// <summary>
        /// There are no comments for Property Operator in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::RuleService.Models.Expressions.ExpressionUnaryOperator Operator
        {
            get
            {
                return this._Operator;
            }
            set
            {
                this.OnOperatorChanging(value);
                this._Operator = value;
                this.OnOperatorChanged();
                this.OnPropertyChanged("Operator");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::RuleService.Models.Expressions.ExpressionUnaryOperator _Operator;
        partial void OnOperatorChanging(global::RuleService.Models.Expressions.ExpressionUnaryOperator value);
        partial void OnOperatorChanged();
        /// <summary>
        /// There are no comments for Property Operand in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::RuleService.Models.Expressions.Expression Operand
        {
            get
            {
                return this._Operand;
            }
            set
            {
                this.OnOperandChanging(value);
                this._Operand = value;
                this.OnOperandChanged();
                this.OnPropertyChanged("Operand");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::RuleService.Models.Expressions.Expression _Operand;
        partial void OnOperandChanging(global::RuleService.Models.Expressions.Expression value);
        partial void OnOperandChanged();
    }
    /// <summary>
    /// There are no comments for ExpressionBinaryOperation in the schema.
    /// </summary>
    public partial class ExpressionBinaryOperation : Expression
    {
        /// <summary>
        /// Create a new ExpressionBinaryOperation object.
        /// </summary>
        /// <param name="operator">Initial value of Operator.</param>
        /// <param name="firstOperand">Initial value of FirstOperand.</param>
        /// <param name="secondOperand">Initial value of SecondOperand.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static ExpressionBinaryOperation CreateExpressionBinaryOperation(global::RuleService.Models.Expressions.ExpressionBinaryOperator @operator, global::RuleService.Models.Expressions.Expression firstOperand, global::RuleService.Models.Expressions.Expression secondOperand)
        {
            ExpressionBinaryOperation expressionBinaryOperation = new ExpressionBinaryOperation();
            expressionBinaryOperation.Operator = @operator;
            if ((firstOperand == null))
            {
                throw new global::System.ArgumentNullException("firstOperand");
            }
            expressionBinaryOperation.FirstOperand = firstOperand;
            if ((secondOperand == null))
            {
                throw new global::System.ArgumentNullException("secondOperand");
            }
            expressionBinaryOperation.SecondOperand = secondOperand;
            return expressionBinaryOperation;
        }
        /// <summary>
        /// There are no comments for Property Operator in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::RuleService.Models.Expressions.ExpressionBinaryOperator Operator
        {
            get
            {
                return this._Operator;
            }
            set
            {
                this.OnOperatorChanging(value);
                this._Operator = value;
                this.OnOperatorChanged();
                this.OnPropertyChanged("Operator");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::RuleService.Models.Expressions.ExpressionBinaryOperator _Operator;
        partial void OnOperatorChanging(global::RuleService.Models.Expressions.ExpressionBinaryOperator value);
        partial void OnOperatorChanged();
        /// <summary>
        /// There are no comments for Property FirstOperand in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::RuleService.Models.Expressions.Expression FirstOperand
        {
            get
            {
                return this._FirstOperand;
            }
            set
            {
                this.OnFirstOperandChanging(value);
                this._FirstOperand = value;
                this.OnFirstOperandChanged();
                this.OnPropertyChanged("FirstOperand");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::RuleService.Models.Expressions.Expression _FirstOperand;
        partial void OnFirstOperandChanging(global::RuleService.Models.Expressions.Expression value);
        partial void OnFirstOperandChanged();
        /// <summary>
        /// There are no comments for Property SecondOperand in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::RuleService.Models.Expressions.Expression SecondOperand
        {
            get
            {
                return this._SecondOperand;
            }
            set
            {
                this.OnSecondOperandChanging(value);
                this._SecondOperand = value;
                this.OnSecondOperandChanged();
                this.OnPropertyChanged("SecondOperand");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::RuleService.Models.Expressions.Expression _SecondOperand;
        partial void OnSecondOperandChanging(global::RuleService.Models.Expressions.Expression value);
        partial void OnSecondOperandChanged();
    }
    /// <summary>
    /// There are no comments for ExpressionBinaryOperator in the schema.
    /// </summary>
    public enum ExpressionBinaryOperator
    {
        Or = 0,
        And = 1
    }
    /// <summary>
    /// There are no comments for ExpressionUnaryOperator in the schema.
    /// </summary>
    public enum ExpressionUnaryOperator
    {
        Not = 0
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Rules in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RuleService.Models.Rule> Rules
        {
            get
            {
                if ((this._Rules == null))
                {
                    this._Rules = base.CreateQuery<global::RuleService.Models.Rule>("Rules");
                }
                return this._Rules;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RuleService.Models.Rule> _Rules;
        /// <summary>
        /// There are no comments for RuleVariables in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RuleService.Models.RuleVariable> RuleVariables
        {
            get
            {
                if ((this._RuleVariables == null))
                {
                    this._RuleVariables = base.CreateQuery<global::RuleService.Models.RuleVariable>("RuleVariables");
                }
                return this._RuleVariables;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RuleService.Models.RuleVariable> _RuleVariables;
        /// <summary>
        /// There are no comments for Rules in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToRules(global::RuleService.Models.Rule rule)
        {
            base.AddObject("Rules", rule);
        }
        /// <summary>
        /// There are no comments for RuleVariables in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToRuleVariables(global::RuleService.Models.RuleVariable ruleVariable)
        {
            base.AddObject("RuleVariables", ruleVariable);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""RuleService.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Rule"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""Expression"" Type=""RuleService.Models.Expressions.Expression"" />
        <NavigationProperty Name=""Variables"" Type=""Collection(RuleService.Models.RuleVariable)"" />
      </EntityType>
      <EntityType Name=""RuleVariable"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""State"" Type=""Edm.Boolean"" Nullable=""false"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""RuleService.Models.Expressions"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <ComplexType Name=""Expression"" Abstract=""true"" />
      <ComplexType Name=""ExpressionVariable"" BaseType=""RuleService.Models.Expressions.Expression"">
        <Property Name=""RuleVariableId"" Type=""Edm.Int32"" Nullable=""false"" />
      </ComplexType>
      <ComplexType Name=""ExpressionUnaryOperation"" BaseType=""RuleService.Models.Expressions.Expression"">
        <Property Name=""Operator"" Type=""RuleService.Models.Expressions.ExpressionUnaryOperator"" Nullable=""false"" />
        <Property Name=""Operand"" Type=""RuleService.Models.Expressions.Expression"" Nullable=""false"" />
      </ComplexType>
      <ComplexType Name=""ExpressionBinaryOperation"" BaseType=""RuleService.Models.Expressions.Expression"">
        <Property Name=""Operator"" Type=""RuleService.Models.Expressions.ExpressionBinaryOperator"" Nullable=""false"" />
        <Property Name=""FirstOperand"" Type=""RuleService.Models.Expressions.Expression"" Nullable=""false"" />
        <Property Name=""SecondOperand"" Type=""RuleService.Models.Expressions.Expression"" Nullable=""false"" />
      </ComplexType>
      <EnumType Name=""ExpressionBinaryOperator"">
        <Member Name=""Or"" Value=""0"" />
        <Member Name=""And"" Value=""1"" />
      </EnumType>
      <EnumType Name=""ExpressionUnaryOperator"">
        <Member Name=""Not"" Value=""0"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Rules"" EntityType=""RuleService.Models.Rule"">
          <NavigationPropertyBinding Path=""Variables"" Target=""RuleVariables"" />
        </EntitySet>
        <EntitySet Name=""RuleVariables"" EntityType=""RuleService.Models.RuleVariable"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
